### ISSUE TITLE
 Can't pickle local object 'CVDB.<locals>.transform_center_crop'

### ISSUE THREAD

**Issue by amitsoniR** [AlekseyKorshuk/huggingnft#3]
(pygpucuda) D:\python\Deep CS\DDN-master>python sr_test.py
Traceback (most recent call last):
  File "sr_test.py", line 50, in <module>
    for data in dataloader:
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\site-packages\torch\utils\data\dataloader.py", line 384, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\site-packages\torch\utils\data\dataloader.py", line 1048, in __init__
    w.start()
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CVDB.<locals>.transform_center_crop'

(pygpucuda) D:\python\Deep CS\DDN-master>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\python\Deep CS\DDN-master\sr_test.py", line 50, in <module>
    for data in dataloader:
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\site-packages\torch\utils\data\dataloader.py", line 384, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\site-packages\torch\utils\data\dataloader.py", line 1048, in __init__
    w.start()
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\amits\anaconda3\envs\pygpucuda\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by Chris1nexus** [comment]
Hello Amit, I believe you raised an issue in the wrong repository: the sr_test.py file belongs to this other repo https://github.com/edongdongchen/DDN/blob/master/sr_test.py

**Comment by amitsoniR** [comment]
yeah, sorry, you are correct!
